config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'todos#index'

   resources :todos  do
      member do 
          post 'complete'
          post 'active'
      end
end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	enum status:[:active,:completed]
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
before_action :find_todo, only: [ :edit, :update, :destroy, :active, :complete]
	def index
		@todo = Todo.new
		@todos = Todo.all
		if params[ :filter ].present?
			@todos = @todos.active if params[ :filter ] == "active"
			@todos = @todos.completed if params[ :filter ] == "completed"
		end
	end

	def create
		@todo =Todo.new(todo_params)
		if  @todo.save
			redirect_to root_path
		else
			render  :index			
		end
	end

	def edit
			
	end

	def update
		if @todo.update(todo_params)
			redirect_to root_path
		else
			render  :edit
		end		
	end

	def complete
		@todo.completed!
		redirect_to root_path		
	end

	def active
		@todo.active!
		redirect_to root_path
	end

	def destroy
		@todo.destroy
		redirect_to root_path
	end

	private

	def find_todo
		@todo = Todo.find(params[ :id])		
	end

	def todo_params
		params.require( :todo) .permit( :content)		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodosApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%  if  user_signed_in?  %>
	Hello  <%=current_user.name %>
	<%= link_to "Log out", destroy_user_session_path, method: "delete" %>
	<%= link_to "Edit", edit_user_registration_path %>
	<%  else  %>
	<%= link_to "Sign up", new_user_registration_path  %>
	<%= link_to "Log in", new_user_session_path %>
	<%  end  %>
	

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%=  form_for @todo do |f| %>
<%= f.text_field :content, placeholder:"Enter Todos" %>
<%= f.submit %>
<% end %>

app/views/todos/_nav.html.erb
<p class="nav nav-pills">

	
	<li role ="presentation" class = "na"><%= link_to "Show All", todos_path(filter:"all") %>
	</li>
	

	
	<li role ="presentation" class = "na"><%= link_to "Todo", todos_path(filter:"active") %>
	</li>
	

	
	<li role ="presentation" class = "na"><%= link_to "Completed", todos_path(filter:"completed") %>
	</li>
	

</p>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render  "form" %>

app/views/todos/index.html.erb
<h1>TodoList</h1>
<%= render  "form" %>
<%= render  "nav"%>
<div>
	<br>
	<% @todos.each do |todo| %>
	<p>
		<% if  todo.completed? %>
				<div  class = "cpl">	
				<%= todo.content %>
				</div>				
		<% else %>
			<%= todo.content %>
		<% end %>

		
		<% if  todo.active? %>
			<%= link_to "Done", complete_todo_path(todo), method: "post" %>
		<% else %>
			<%= link_to "Undo", active_todo_path(todo), method: "post" %>
		<% end %>
		
		<%= link_to "Edit", edit_todo_path(todo) %>
		<%= link_to "Delete", todo_path(todo) , method:"delete" ,data: { confirm: "Delete?" }%>
		
		
	</p>
	<% end %>
</div>